name: automatic-release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          # Assets to upload to the release
          files: |
            LICENSE
            check_nvme.sh
